version: "3.6"
services:
  mongo:
    image: mongo:latest
    ports:
      - "27100:27017"
  cafe:
    image: textile-cafe
    build: .
    ports:
      - "8000:8000"
      - "9000:9000"
      - "4001:4001"
      - "4002:4002"
