version: "3.6"
services:
  mongo:
    image: mongo:latest
    ports:
      - "27100:27017"
  central:
    image: textile-cafe
    build: .
    ports:
      - "8000:8000"
      - "9000:9000"
    environment:
      - VERSION=0.0.1
      - BIND=0.0.0.0:8000
      - TOKEN_SECRET=swarmmmmmmmm
      - DB_HOSTS=mongo:27017
      - DB_NAME=textile_db
      - REF_KEY=woohoo!
