version: "3.6"
services:
  mongo:
    image: mongo:latest
    ports:
      - "27100:27017"
  central:
    image: central
    build: central
    ports:
      - "8000:8000"
    environment:
      - VERSION=0.0.1
      - BIND=0.0.0.0:8000
      - TOKEN_SECRET=swarmmmmmmmm
      - DB_HOSTS=mongo:27017
      - DB_NAME=textile_db
      - REF_KEY=woohoo!
  relay:
    image: relay
    build: relay
    ports:
      - "4001:4001"
    environment:
      - RELAY=okaydokay
      - SWARM_PORT=4001
