version: 2
jobs:
  build:
    docker:
      - image: textile/circleci:0.4.15
      - image: mongo:3.4.10
    working_directory: /go/src/github.com/textileio/textile-go
    steps:
      - checkout
      - run: dep ensure
      - run: go get -u github.com/kardianos/govendor
      - run:
          name: install central
          command: |
            cd central
            govendor init
            govendor add +external
            go install -v ./...
      - run:
          name: install relay
          command: |
            cd relay
            govendor init
            govendor add +external
            go install -v ./...
      - run:
          name: run and test all
          command: |
            central &
            relay &
            sleep 5
            ./test_compile.sh
          environment:
            VERSION: 0.0.1
            BIND: 0.0.0.0:8000
            HOST: 0.0.0.0:8000
            TOKEN_SECRET: swarmmmmmmmm
            DB_HOSTS: 0.0.0.0:27017
            DB_NAME: textile_db
            REF_KEY: woohoo!
            RELAY: testdummythread
      - run: go get -u github.com/asticode/go-astilectron-bundler/...
      - run: make build_desktop
