[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.2.0"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/globalsign/mgo"

[[constraint]]
  name = "github.com/nbutton23/zxcvbn-go"
  version = "0.1.0"

[[constraint]]
  name = "github.com/segmentio/ksuid"
  version = "1.0.1"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"
