// Code generated by protoc-gen-go. DO NOT EDIT.
// source: thread_item.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ThreadItem struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Peers                int32    `protobuf:"varint,3,opt,name=peers,proto3" json:"peers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ThreadItem) Reset()         { *m = ThreadItem{} }
func (m *ThreadItem) String() string { return proto.CompactTextString(m) }
func (*ThreadItem) ProtoMessage()    {}
func (*ThreadItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_thread_item_7fbb9c2a0475535d, []int{0}
}
func (m *ThreadItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThreadItem.Unmarshal(m, b)
}
func (m *ThreadItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThreadItem.Marshal(b, m, deterministic)
}
func (dst *ThreadItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThreadItem.Merge(dst, src)
}
func (m *ThreadItem) XXX_Size() int {
	return xxx_messageInfo_ThreadItem.Size(m)
}
func (m *ThreadItem) XXX_DiscardUnknown() {
	xxx_messageInfo_ThreadItem.DiscardUnknown(m)
}

var xxx_messageInfo_ThreadItem proto.InternalMessageInfo

func (m *ThreadItem) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ThreadItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ThreadItem) GetPeers() int32 {
	if m != nil {
		return m.Peers
	}
	return 0
}

func init() {
	proto.RegisterType((*ThreadItem)(nil), "ThreadItem")
}

func init() { proto.RegisterFile("thread_item.proto", fileDescriptor_thread_item_7fbb9c2a0475535d) }

var fileDescriptor_thread_item_7fbb9c2a0475535d = []byte{
	// 112 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0xc9, 0x28, 0x4a,
	0x4d, 0x4c, 0x89, 0xcf, 0x2c, 0x49, 0xcd, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x72, 0xe3,
	0xe2, 0x0a, 0x01, 0x0b, 0x7a, 0x96, 0xa4, 0xe6, 0x0a, 0xf1, 0x71, 0x31, 0x65, 0xa6, 0x48, 0x30,
	0x2a, 0x30, 0x6a, 0x70, 0x06, 0x31, 0x65, 0xa6, 0x08, 0x09, 0x71, 0xb1, 0xe4, 0x25, 0xe6, 0xa6,
	0x4a, 0x30, 0x81, 0x45, 0xc0, 0x6c, 0x21, 0x11, 0x2e, 0xd6, 0x82, 0xd4, 0xd4, 0xa2, 0x62, 0x09,
	0x66, 0x05, 0x46, 0x0d, 0xd6, 0x20, 0x08, 0xc7, 0x89, 0x25, 0x8a, 0xa9, 0x20, 0x29, 0x89, 0x0d,
	0x6c, 0xa8, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x7d, 0x77, 0xda, 0xa5, 0x69, 0x00, 0x00, 0x00,
}
